[package]
name = "chess_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "chess_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module"] }
chess = "3.0.0"
rand = "0.9.0"
